#!/bin/bash

/usr/bin/env -i \
	PATH=$CROSSPI_HOST_DIR/bin:$PATH \
	LD_LIBRARY_PATH=$CROSSPI_HOST_DIR/lib:$LD_LIBRARY_PATH \
	ACLOCAL_FLAGS="-I $CROSSPI_HOST_DIR/share/aclocal" \
	PKG_CONFIG_PATH=$CROSSPI_HOST_DIR/lib/pkgconfig:$PKG_CONFIG_PATH \
	CPPFLAGS=-I$CROSSPI_HOST_DIR/include \
	LDFLAGS=-L$CROSSPI_HOST_DIR/lib \
	\
	CROSSPI_HOME=$CROSSPI_HOME \
	CROSSPI_HOST_DIR=$CROSSPI_HOST_DIR \
	CROSSPI_SYSROOT_DIR=$CROSSPI_SYSROOT_DIR \
	CROSSPI_TARGET_DIR=$CROSSPI_TARGET_DIR \
	CROSSPI_SOURCES_DIR=$CROSSPI_SOURCES_DIR \
	CROSSPI_TOOLS_DIR=$CROSSPI_TOOLS_DIR \
	CROSSPI_TOOLCHAIN=$CROSSPI_TOOLCHAIN \
	\
	HOME=$HOME \
	TERM=$TERM \
	\
	DESTDIR=$CROSSPI_HOST_DIR \
	\
	/bin/bash --rcfile <(cat ~/.bashrc ; echo 'PS1="\[\033[0;33m\][native x86]\[\033[00m\] $PS1"' ; echo 'alias cross=$CROSSPI_HOME/cross-env.sh' ; echo $1) +h
