#!/bin/bash

PKG_NAME=gcc-4.9.2

PKG_REQUIRE_SEPERATED_BUILD_DIR=true
PKG_NO_CLEANUP=true

pkg_build() {
  make -j${CROSSPI_BUILD_NPROC} all-target-libgcc
}

pkg_install() {
  make install-target-libgcc
}