#!/bin/bash

PKG_NAME=libtool-2.4.5
PKG_URL=http://ftpmirror.gnu.org/libtool/${PKG_NAME}.tar.gz

pkg_configure() {
	${PKG_SRC_DIR}/configure --prefix=${CROSSPI_TOOLCHAIN_DIR}/usr --program-prefix=${CROSSPI_TARGET}- --host=${CROSSPI_TARGET} --target=${CROSSPI_TARGET} --build=${CROSSPI_BUILD}
}

pkg_build() {
	make -j${CROSSPI_BUILD_NPROC}
}

pkg_install() {
	make install
}
