#!/bin/bash

download_raspberrypi_tools() {
        if [ ! -d "$CROSSPI_HOME/tools/.git" ]; then
                log_info_msg "Downloading RPI cross-compilation tools..."
                git clone https://github.com/raspberrypi/tools.git &> /dev/null
                evaluate_retval
        fi
}

update_raspberrypi_tools() {
        log_info_msg "Updating RPI cross-compilation tools..."
        if [ ! -d "$CROSSPI_HOME/tools/.git" ]; then
                log_info_msg "\n"
                log_failure_msg "Can't update, tools not installed !"
                exit 1
        fi

        cd $CROSSPI_HOME/tools/
        git reset --hard &> /dev/null
        git clean -fd &> /dev/null
        git pull &> /dev/null
        evaluate_retval
        cd $CROSSPI_HOME
}
