#!/bin/bash

PKG_NAME=x264
PKG_URL=ftp://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20141218-2245.tar.bz2

PKG_EXTRACTED_DIRNAME=x264-snapshot-20141218-2245

pkg_configure() {
	${PKG_SRC_DIR}/configure	--prefix=/usr \
					--host=$CROSSPI_TARGET \
					--cross-prefix=$CROSS \
					--enable-pic \
					--enable-shared \
					--enable-strip \
					--disable-asm \
					--disable-cli
}

pkg_build() {
	make -j${CROSSPI_BUILD_NPROC}
}

pkg_install() {
	make install
}
